module.exports = {
    REQUEST_FAILURE: 'Failed to',
    DATA_NOT_FOUND: 'Data not found.',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    DATABASE_CONNECTED: 'Connection has been established successfully.',
    AUTH_MISSING: 'Authorization header is missing',
    TOKEN_EXPIRED: 'Token is expired',
    TOKEN_INVALID: 'Token is invalid',
    ACCESS_REQUIRED: 'Valid access required',
    EMAIL_INCORRECT: 'Your email id is not registered with account.',
    ID_NOT_FOUND: 'Id not found',
    ADD_DATA: 'added successfully.',
    GET_SUCCESS: 'getting successfully.',
    UPDATE_SUCCESS: 'updated successfully.',
    DELETE_SUCCESS: 'deleted successfully',
    REGISTER_SUCCESS: 'Congratulation! You are registered successfully.',
    USER_NOT_FOUND: `User with this email doesn't exist.`,
    ALREADY_EXIST: `Email is already registered with another account.`,
    LOGIN_SUCCESS: 'You are login successfully.',
    INCORRECT_CREDENTIALS: 'Credential does not match.',
};